version: '3'

services:
  nginx:
    image: 'bitnami/nginx:latest'
    container_name: nginx
    user: root
    ports:
    - '80:8080'
    - '443:8443'
    volumes:
    - 'nginx_data:/bitnami'
    - 'certs_data:/etc/letsencrypt:ro'
    - './my_vhost.conf:/bitnami/nginx/conf/vhosts/my_vhost.conf:ro'
    - './dist:/app:ro'

volumes:
  nginx_data:
    driver: local
  certs_data:
    driver: local

networks:
  default:
    external:
      name: hhnet