version: '3'

services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: mariadb
    ports:
    - '3306:3306'
    volumes:
    - 'mariadb_data:/bitnami'
    environment:
    - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
    - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

volumes:
  mariadb_data:
    driver: local

networks:
  default:
    external:
      name: hhnet